// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDromVSTvZx5dXUy8tX133rrTg1rROwLL8',
    appId: '1:291922118026:web:09c239d586fd231706f473',
    messagingSenderId: '291922118026',
    projectId: 'blogever8',
    authDomain: 'blogever8.firebaseapp.com',
    storageBucket: 'blogever8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBipS4xzruW-UCSARIQyX5yUi7n0Wehf_k',
    appId: '1:291922118026:android:6ff9d65da5f3c18006f473',
    messagingSenderId: '291922118026',
    projectId: 'blogever8',
    storageBucket: 'blogever8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZzcGI-BcrwPSwDmj7nAkNd7mYelGJ0tI',
    appId: '1:291922118026:ios:b769e776353cb34606f473',
    messagingSenderId: '291922118026',
    projectId: 'blogever8',
    storageBucket: 'blogever8.appspot.com',
    iosClientId: '291922118026-a7pk0c01ufhds0niqeb87rkkthptdk3b.apps.googleusercontent.com',
    iosBundleId: 'com.krzysztofkochel.blogever',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZzcGI-BcrwPSwDmj7nAkNd7mYelGJ0tI',
    appId: '1:291922118026:ios:b769e776353cb34606f473',
    messagingSenderId: '291922118026',
    projectId: 'blogever8',
    storageBucket: 'blogever8.appspot.com',
    iosClientId: '291922118026-a7pk0c01ufhds0niqeb87rkkthptdk3b.apps.googleusercontent.com',
    iosBundleId: 'com.krzysztofkochel.blogever',
  );
}
